name: tekartik_amazon_ses_node
description: Send email in node environment
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.11.1'
  process_run:
dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
  # needed node dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
