name: tekartik_aws_ses_node
description: Send email in node environment
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  tekartik_js_utils_interop:
    git:
      url: https://github.com/tekartik/js_utils.dart
      path: js_utils_interop
      ref: dart3a
    version: '>=0.1.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.11.1'
  process_run: ">=1.2.1+1"
  tekartik_core_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: core_node
      ref: dart3a
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  # needed node dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
  tekartik_app_node_build_menu:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      ref: dart3a
      path: app_build_menu
    version: '>=0.3.0'
